# AAO GALAH RESEARCH JAN-APR 2016

### Missy McIntosh, Gayandhi de Silva, Jeffrey Simpson

#### Check if there are any known open clusters in GALAH

In [8]:
import numpy as np
import starbase
from astropy import units as u
from astropy.coordinates import SkyCoord
from astropy.coordinates import FK5

# Read in 2Mass input database Name, RA, and DEC information
twomass_data = np.genfromtxt('test.csv', delimiter=',', names=True, dtype=float)

# Read in Webda observed Name, RA, and DEC information
webda_data = np.genfromtxt('ad2000.coo', delimiter='\t', names=True, dtype=None)
#webda_data['ra'] = webda_data

subset = [[10.5680911, 109.8102128, 27.831013, 1.1438403, 276.1315219, 1, 400],[-89.969946899999997, -89.9304625, 5,5,-89.915107199999994,5,-89.915107199999994]]


test = (webda_data[2][3].decode('UTF-8'))
print(test)
#print(np.float(test))

c = SkyCoord(ra=10.68458*u.degree, dec=41.26917*u.degree)
c.to_string('decimal')

test = starbase.Starbase_readtable('ad2000.coo')

+33 33 29.76


AttributeError: 'module' object has no attribute 'Starbase_readtable'

In [275]:
def pbsearch(sorted_data, subset, tolerance):
    tol = tolerance

    # return index if it exists, otherwise, print "not found"
    matched_arr = []
    for a in subset: 
        ra = sorted_data
        n = len(ra)
        for element in np.arange(0,n):
            n = len(ra)
            #print('loop: ', element)
            if a - tol > ra[int(n/2)]:
                ra = ra[int(n/2):n]
            elif a + tol < ra[int(n/2)]:
                ra = ra[0:int(n/2)]
            else:
                match = ra[int(n/2)]
                print('match!  searched', a, " found", match, " which is", np.absolute(a - ra[int(n/2)]), "away")
                matched_arr.append(match)
                break
                
            if n > 1:
                continue
            else:
                print(a, "not found within tolerance")
                break
        
    return(matched_arr)

In [276]:
# Search first by RA and then by DEC
# sort RA values to make the search faster
ra_sorted = np.sort(twomass_data, order='ra')
ra = ra_sorted['ra']
print(twomass_data["ra"], "\n", "\n", ra_sorted["ra"])

# return subset RAs found within sorted data
tol = 0.0005
ra_arr = pbsearch(ra, subset[0], tol)
print("-"*100)

[  10.5680911  109.8102128   27.8310139    1.1438403  276.1315219] 
 
 [   1.1438403   10.5680911   27.8310139  109.8102128  276.1315219]
match!  searched 10.5680911  found 10.5680911  which is 0.0 away
match!  searched 109.8102128  found 109.8102128  which is 0.0 away
match!  searched 27.831013  found 27.8310139  which is 8.99999999859e-07 away
match!  searched 1.1438403  found 1.1438403  which is 0.0 away
match!  searched 276.1315219  found 276.1315219  which is 0.0 away
1 not found within tolerance
400 not found within tolerance
----------------------------------------------------------------------------------------------------


In [277]:
# retrieve the DEC and indicies of the found subset RAs
ind_arr = []
dec_arr = []
for ra in ra_arr:
    ind = np.where(twomass_data['ra'] == ra)[0][0]
    ind_arr.append(ind)
    dec = twomass_data['dec'][ind]
    dec_arr.append(dec)

In [278]:
# check that the DEC values are w/i tolerence and return matched indices
matched_ind = []
for i in np.arange(0,len(dec_arr)):
    a = subset[1][i]
    dec = dec_arr[i]
    if np.absolute(a - dec) < tol:
        matched_ind.append(ind_arr[i])
print(matched_ind)

[0, 4]


In [279]:
# select info on the matched RA and DECs
twomass_data['galah_id'][matched_ind]

array([ 0.,  4.])